CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  credits INTEGER NOT NULL DEFAULT 6,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
